### ISSUE TITLE
DOS-formatted Tissues?.txt files

### ISSUE THREAD

**Issue by humanpaingeneticslab** [TiffanyAmariuta/TCSC#2]
The Tissues{A,B,C}.txt files are all DOS formatted, such that when used under UNIX / Linux there's an extra '\r' character - this makes the downloading 'wget' fail in step 5.

One could use 'flip -u TissuesA.txt' to convert these files for UNIX / Linux; 
https://ccrma.stanford.edu/~craig/utility/flip/

**Comment by zhangpicb** [comment]
Hi@humanpaingeneticslab 

How to get Tissues{A,B,C}.txt ?

Thanks in advanced!

**Comment by humanpaingeneticslab** [comment]
Hello,

They’re in this folder:
https://github.com/TiffanyAmariuta/TCSC/tree/main/analysis/

A+

**Comment by TiffanyAmariuta** [comment]
Thank you for pointing this out! I have corrected the formatting so the wget should not fail in step 5. I have also corrected the paths for the Tissue files to point to the analysis folder.
